#!/usr/bin/env node
// Generates config.js at build time from environment variables.
// Used by Vercel deploys. Local dev still uses a hand-written config.js
// copied from config.example.js — this script is a no-op there.
const fs = require("fs");

const url = process.env.SUPABASE_URL || "";
const key = process.env.SUPABASE_ANON_KEY || "";

if (!url || !key) {
  console.log("[build-config] No Supabase env vars set — skipping config.js (guest-only deploy).");
  // Write an empty stub so the GET 404 noise goes away in production
  fs.writeFileSync("config.js", "// No Supabase configured. window.APP_CONFIG left undefined.\n");
  process.exit(0);
}

const out = `// Auto-generated by build-config.js — do not edit.\nwindow.APP_CONFIG = ${JSON.stringify(
  { SUPABASE_URL: url, SUPABASE_ANON_KEY: key },
  null,
  2
)};\n`;

fs.writeFileSync("config.js", out);
console.log("[build-config] Wrote config.js for", url);
